[package]
name = "vsdb_slot_db"
version = "0.8.0"
edition = "2021"
keywords = ["index", "cache", "timestamp", "slot", "database"]
license = "MIT"
authors = ["hui.fan@mail.ru"]
description = "A skip-list like index cache"
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb"

[dependencies]
ruc = { workspace = true }
vsdb = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"
rand = { workspace = true }

[features]
default = ["compress", "msgpack_codec"]

compress = ["vsdb/compress"]

bcs_codec = ["vsdb/bcs_codec"]
json_codec = ["vsdb/json_codec"]
msgpack_codec = ["vsdb/msgpack_codec"]

[[bench]]
name = "0_slot_db_reverse_swap_order"
harness = false

[[bench]]
name = "1_slot_db_positive"
harness = false

[[bench]]
name = "2_slot_db_reverse"
harness = false
